### ISSUE TITLE
some problems

### ISSUE THREAD

**Issue by asteria25** [kevinduh/sockeye-recipes#30]
I am using the command: ../../../scripts/train-curriculum.sh -p rs1.hpm -e sockeye-curriculum

There are two problems:
1.
[ERROR:root] Uncaught exception
Traceback (most recent call last):
  File "/opt/anaconda3/envs/sockeye-curriculum/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/anaconda3/envs/sockeye-curriculum/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/anaconda3/envs/sockeye-curriculum/lib/python3.6/site-packages/sockeye/prepare_data.py", line 93, in <module>
    main()
  File "/opt/anaconda3/envs/sockeye-curriculum/lib/python3.6/site-packages/sockeye/prepare_data.py", line 32, in main
    prepare_data(args)
  File "/opt/anaconda3/envs/sockeye-curriculum/lib/python3.6/site-packages/sockeye/prepare_data.py", line 90, in prepare_data
    curriculum_score_file=args.curriculum_score_file)
  File "/opt/anaconda3/envs/sockeye-curriculum/lib/python3.6/site-packages/sockeye/data_io.py", line 669, in prepare_data
    sample_scores = [int(line.strip()) for line in curriculum_score_file if line.strip()]
  File "/opt/anaconda3/envs/sockeye-curriculum/lib/python3.6/site-packages/sockeye/data_io.py", line 669, in <listcomp>
    sample_scores = [int(line.strip()) for line in curriculum_score_file if line.strip()]
ValueError: invalid literal for int() with base 10: '<!DOCTYPE html>'
 2. 
[ERROR:root] Uncaught exception
Traceback (most recent call last):
  File "/opt/anaconda3/envs/sockeye-curriculum/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/anaconda3/envs/sockeye-curriculum/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/anaconda3/envs/sockeye-curriculum/lib/python3.6/site-packages/sockeye/train.py", line 969, in <module>
    main()
  File "/opt/anaconda3/envs/sockeye-curriculum/lib/python3.6/site-packages/sockeye/train.py", line 835, in main
    train(args)
  File "/opt/anaconda3/envs/sockeye-curriculum/lib/python3.6/site-packages/sockeye/train.py", line 889, in train
    output_folder=output_folder)
  File "/opt/anaconda3/envs/sockeye-curriculum/lib/python3.6/site-packages/sockeye/train.py", line 260, in create_data_iters_and_vocabs
    fill_up=args.fill_up,
AttributeError: 'Namespace' object has no attribute 'fill_up'

Can someone help me fix these two errors?
Thanks.

**Comment by kevinduh** [comment]
Can you check if the data is downloaded properly? Error 1 suggest maybe something is missing with the `curriculum_sent.scores` file. Can you paste a few lines for that file and also check if the length? If you're following the same recipe, it should be 151626 lines. 

Error 2 might be something else, but let's first figure out Error 1.

**Comment by asteria25** [comment]
Thanks for your response.

The curriculum_sent.scores file has 151627 lines. I have changed the download website because the original website is 'unreachable'. I changed it into  
https://github.com/Este1le/curriculum_learning_scores/tree/master/scores/data_scores_ted/ted.sentence_average_rank.de.bk.
Could this be the reason?

**Comment by kevinduh** [comment]
Can you show the first few lines and last few lines of that file you have? e.g. `head curriculum_sent.scores`

**Comment by asteria25** [comment]
The curriculum_sent.scores file:

The first few lines:
```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
  <link rel="dns-prefetch" href="https://github.githubassets.com">
  <link rel="dns-prefetch" href="https://avatars0.githubusercontent.com">
  <link rel="dns-prefetch" href="https://avatars1.githubusercontent.com">
  <link rel="dns-prefetch" href="https://avatars2.githubusercontent.com">
  <link rel="dns-prefetch" href="https://avatars3.githubusercontent.com">
  <link rel="dns-prefetch" href="https://github-cloud.s3.amazonaws.com">
  <link rel="dns-prefetch" href="https://user-images.githubusercontent.com/">

```
The last few lines:
```
      <div class="octocat-spinner my-6 js-details-dialog-spinner"></div>
    </details-dialog>
  </details>
</template>

  <div class="Popover js-hovercard-content position-absolute" style="display: none; outline: none;" tabindex="0">
  <div class="Popover-message Popover-message--bottom-left Popover-message--large Box box-shadow-large" style="width:360px;">
  </div>
</div>


  </body>
</html>
```

**Comment by Este1le** [comment]
Hi, please use the link to the raw file: https://raw.githubusercontent.com/Este1le/curriculum_learning_scores/master/scores/data_scores_ted/ted.sentence_average_rank.de.bk instead of the link to the html page: https://github.com/Este1le/curriculum_learning_scores/tree/master/scores/data_scores_ted/ted.sentence_average_rank.de.bk. The curriculum_sent.scores file should contain only numbers.

**Comment by asteria25** [comment]
OK,I'll try.

**Comment by asteria25** [comment]
Error 1 is solved. Thanks for your help.

**Comment by asteria25** [comment]
I still have error 2. What could be the problem? Thanks.

**Comment by kevinduh** [comment]
Can you provide more details? Please provide the command line and the file you used, esp. the hpm file.

**Comment by asteria25** [comment]
I use the command in /egs/curriculum/de-en : ../../../scripts/train-curriculum.sh -p rs1.hpm -e sockeye-curriculum
the other files are the same as the project

**Comment by asteria25** [comment]
I also changed the website in the `install_tools.sh` file. But I have changed it back, deleted the file and reinstalled.And rerun the later commands until this command line report an error.

Here's the log.
` ../../../scripts/train-curriculum.sh -p rs1.hpm -e sockeye-curriculum
--use-cpu
get-device.sh: On d5a465196a70 Using CPU because no free GPUs. Mon Sep 21 00:32:46 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.64.00    Driver Version: 440.64.00    CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla P100-PCIE...  Off  | 00000000:B5:00.0 Off |                    0 |
| N/A   44C    P0    86W / 250W |  12184MiB / 12198MiB |    100%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla P100-PCIE...  Off  | 00000000:C1:00.0 Off |                    0 |
| N/A   34C    P0    35W / 250W |   1943MiB / 12198MiB |    100%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
+-----------------------------------------------------------------------------+
[INFO:__main__] Adjusting maximum length to reserve space for a BOS/EOS marker. New maximum length: (100, 100)
[INFO:sockeye.vocab] =============================
[INFO:sockeye.vocab] Loading/creating vocabularies
[INFO:sockeye.vocab] =============================
[INFO:sockeye.vocab] (1) Surface form vocabularies (source & target)
[INFO:sockeye.vocab] Building vocabulary from dataset(s): ['.//data-bpe//train.bpe-30000.de']
[INFO:sockeye.vocab] Vocabulary: types: 29620/29620/29620/29624 (initial/min_pruned/max_pruned/+special) [min_frequency=1, max_num_types=None, pad_to_multiple_of=None]
[INFO:sockeye.vocab] Building vocabulary from dataset(s): ['.//data-bpe//train.bpe-30000.en']
[INFO:sockeye.vocab] Vocabulary: types: 28055/28055/28055/28059 (initial/min_pruned/max_pruned/+special) [min_frequency=1, max_num_types=None, pad_to_multiple_of=None]
[INFO:sockeye.data_io] Preparing data.
[INFO:sockeye.vocab] Vocabulary saved to "/home/gb504/stu_ftt/sockeye-recipes/egs/curriculum/de-en/rs1/prepared_data/vocab.src.0.json"
[INFO:sockeye.vocab] Vocabulary saved to "/home/gb504/stu_ftt/sockeye-recipes/egs/curriculum/de-en/rs1/prepared_data/vocab.trg.0.json"
[INFO:sockeye.data_io] 151627 sequences of maximum length (100, 100) in './/data-bpe//train.bpe-30000.de' and './/data-bpe//train.bpe-30000.en'.
[INFO:sockeye.data_io] Mean training target/source length ratio: 1.03 (+-0.18)
[INFO:sockeye.data_io] Buckets: [(10, 10), (20, 20), (30, 30), (40, 40), (50, 50), (60, 60), (70, 70), (80, 80), (90, 90), (100, 100)]
[INFO:sockeye.data_io] 151627 samples will be split into 5 shard(s) (requested samples/shard=1000000, min_num_shards=1).
[INFO:sockeye.data_io] Tokens: source 3212953 target 3249777
[INFO:sockeye.data_io] Vocabulary coverage: source 100% target 100%
[INFO:sockeye.data_io] 151627 sequences across 10 buckets
[INFO:sockeye.data_io] 0 sequences did not fit into buckets and were discarded
[INFO:sockeye.data_io] Created bucketed parallel data set. Introduced padding: source=25.3% target=23.1%)
[INFO:sockeye.data_io] Tokens: source 781854 target 804675
[INFO:sockeye.data_io] Vocabulary coverage: source 100% target 100%
[INFO:sockeye.data_io] 47202 sequences across 10 buckets
[INFO:sockeye.data_io] 0 sequences did not fit into buckets and were discarded
[INFO:sockeye.data_io] Writing '/home/gb504/stu_ftt/sockeye-recipes/egs/curriculum/de-en/rs1/prepared_data/shard.00000'
[INFO:sockeye.data_io] Created bucketed parallel data set. Introduced padding: source=19.6% target=18.7%)
[INFO:sockeye.data_io] Tokens: source 1177649 target 1191288
[INFO:sockeye.data_io] Vocabulary coverage: source 100% target 100%
[INFO:sockeye.data_io] 48261 sequences across 10 buckets
[INFO:sockeye.data_io] 0 sequences did not fit into buckets and were discarded
[INFO:sockeye.data_io] Writing '/home/gb504/stu_ftt/sockeye-recipes/egs/curriculum/de-en/rs1/prepared_data/shard.00001'
[INFO:sockeye.data_io] Created bucketed parallel data set. Introduced padding: source=19.6% target=19.5%)
[INFO:sockeye.data_io] Tokens: source 888978 target 890262
[INFO:sockeye.data_io] Vocabulary coverage: source 100% target 100%
[INFO:sockeye.data_io] 36664 sequences across 10 buckets
[INFO:sockeye.data_io] 0 sequences did not fit into buckets and were discarded
[INFO:sockeye.data_io] Writing '/home/gb504/stu_ftt/sockeye-recipes/egs/curriculum/de-en/rs1/prepared_data/shard.00002'
[INFO:sockeye.data_io] Created bucketed parallel data set. Introduced padding: source=22.1% target=22.5%)
[INFO:sockeye.data_io] Tokens: source 331200 target 329727
[INFO:sockeye.data_io] Vocabulary coverage: source 100% target 100%
[INFO:sockeye.data_io] 16726 sequences across 10 buckets
[INFO:sockeye.data_io] 0 sequences did not fit into buckets and were discarded
[INFO:sockeye.data_io] Writing '/home/gb504/stu_ftt/sockeye-recipes/egs/curriculum/de-en/rs1/prepared_data/shard.00003'
[INFO:sockeye.data_io] Created bucketed parallel data set. Introduced padding: source=30.6% target=29.5%)
[INFO:sockeye.data_io] Tokens: source 33272 target 33825
[INFO:sockeye.data_io] Vocabulary coverage: source 100% target 100%
[INFO:sockeye.data_io] 2774 sequences across 10 buckets
[INFO:sockeye.data_io] 0 sequences did not fit into buckets and were discarded
[INFO:sockeye.data_io] Writing '/home/gb504/stu_ftt/sockeye-recipes/egs/curriculum/de-en/rs1/prepared_data/shard.00004'
[INFO:sockeye.data_io] Writing data info to '/home/gb504/stu_ftt/sockeye-recipes/egs/curriculum/de-en/rs1/prepared_data/data.info'
[INFO:sockeye.data_io] Writing data config to '/home/gb504/stu_ftt/sockeye-recipes/egs/curriculum/de-en/rs1/prepared_data/data.config'
[WARNING:__main__] '--checkpoint-frequency' is deprecated, and will be removed in the future.  Please use '--checkpoint-interval'
[INFO:sockeye.utils] Sockeye version 1.18.100, commit bbbed811fb7f7fe8e72445259d4c1a0cdb7a4e51, path /opt/anaconda3/envs/sockeye-curriculum/lib/python3.6/site-packages/sockeye/__init__.py
[INFO:sockeye.utils] MXNet version 1.4.1, path /opt/anaconda3/envs/sockeye-curriculum/lib/python3.6/site-packages/mxnet/__init__.py
[INFO:sockeye.utils] Command: /opt/anaconda3/envs/sockeye-curriculum/lib/python3.6/site-packages/sockeye/train.py -d .//rs1/prepared_data --curriculum-training --curriculum-update-freq 1000 -vs .//data-bpe//valid.bpe-30000.de -vt .//data-bpe//valid.bpe-30000.en --encoder rnn --decoder rnn --rnn-num-hidden 512 --rnn-attention-type dot --rnn-cell-type lstm --rnn-dropout-inputs .0:.0 --rnn-dropout-states .0:.0 --num-embed 512:512 --num-layers 1 --embed-dropout .0:.0 --max-seq-len 100:100 --num-words 30000:30000 --word-min-count 1:1 --checkpoint-frequency 4000 --batch-size 4096 --min-num-epochs 0 --max-num-epochs 100 --max-updates 500000 --keep-last-params 5 --disable-device-locking --decode-and-evaluate -1 --decode-and-evaluate-use-cpu --initial-learning-rate 0.0002 --label-smoothing 0.1 --batch-type word --optimizer adam --gradient-clipping-threshold 1.0 --gradient-clipping-type abs --learning-rate-reduce-factor 0.7 --learning-rate-reduce-num-not-improved 32 --learning-rate-scheduler-type plateau-reduce --learning-rate-decay-optimizer-states-reset best --learning-rate-decay-param-reset --loss cross-entropy --seed 13 --use-cpu -o .//rs1
[INFO:sockeye.utils] Arguments: Namespace(allow_missing_params=False, batch_size=4096, batch_type='word', bucket_width=10, checkpoint_frequency=4000, checkpoint_interval=4000, cnn_activation_type='glu', cnn_hidden_dropout=0.2, cnn_kernel_width=(3, 3), cnn_num_hidden=512, cnn_positional_embedding_type='learned', cnn_project_qkv=False, config=None, conv_embed_add_positional_encodings=False, conv_embed_dropout=0.0, conv_embed_max_filter_width=8, conv_embed_num_filters=(200, 200, 250, 250, 300, 300, 300, 300), conv_embed_num_highway_layers=4, conv_embed_output_dim=None, conv_embed_pool_stride=5, curriculum_training=True, curriculum_update_freq=1000, decode_and_evaluate=-1, decode_and_evaluate_device_id=None, decode_and_evaluate_use_cpu=True, decoder='rnn', decoder_only=False, device_ids=[-1], disable_device_locking=True, dry_run=False, embed_dropout=(0.0, 0.0), embed_weight_init='default', encoder='rnn', fixed_param_names=[], fixed_param_strategy=None, gradient_clipping_threshold=1.0, gradient_clipping_type='abs', gradient_compression_threshold=0.5, gradient_compression_type=None, initial_learning_rate=0.0002, keep_initializations=False, keep_last_params=5, kvstore='device', label_smoothing=0.1, layer_normalization=False, learning_rate_decay_optimizer_states_reset='best', learning_rate_decay_param_reset=True, learning_rate_half_life=10, learning_rate_reduce_factor=0.7, learning_rate_reduce_num_not_improved=32, learning_rate_schedule=None, learning_rate_scheduler_type='plateau-reduce', learning_rate_warmup=0, length_task=None, length_task_layers=1, length_task_weight=1.0, lhuc=None, lock_dir='/tmp', loglevel='INFO', loss='cross-entropy', loss_normalization_type='valid', max_checkpoints=None, max_num_checkpoint_not_improved=32, max_num_epochs=100, max_samples=None, max_seq_len=(100, 100), max_updates=500000, metrics=['perplexity'], min_num_epochs=0, min_samples=None, min_updates=None, momentum=None, monitor_pattern=None, monitor_stat_func='mx_default', no_bucketing=False, num_embed=(512, 512), num_layers=(1, 1), num_words=(30000, 30000), optimized_metric='perplexity', optimizer='adam', optimizer_params=None, output='.//rs1', overwrite_output=False, pad_vocab_to_multiple_of=None, params=None, prepared_data='.//rs1/prepared_data', quiet=False, rnn_attention_coverage_max_fertility=2, rnn_attention_coverage_num_hidden=1, rnn_attention_coverage_type='count', rnn_attention_in_upper_layers=False, rnn_attention_mhdot_heads=None, rnn_attention_num_hidden=None, rnn_attention_type='dot', rnn_attention_use_prev_word=False, rnn_cell_type='lstm', rnn_context_gating=False, rnn_decoder_hidden_dropout=0.2, rnn_decoder_state_init='last', rnn_dropout_inputs=(0.0, 0.0), rnn_dropout_recurrent=(0.0, 0.0), rnn_dropout_states=(0.0, 0.0), rnn_enc_last_hidden_concat_to_embedding=False, rnn_encoder_reverse_input=False, rnn_first_residual_layer=2, rnn_forget_bias=0.0, rnn_h2h_init='orthogonal', rnn_num_hidden=512, rnn_residual_connections=False, rnn_scale_dot_attention=False, seed=13, shared_vocab=False, source=None, source_factor_vocabs=[], source_factors=[], source_factors_combine='concat', source_factors_num_embed=[], source_vocab=None, stop_training_on_decoder_failure=False, target=None, target_vocab=None, transformer_activation_type='relu', transformer_attention_heads=(8, 8), transformer_dropout_act=0.1, transformer_dropout_attention=0.1, transformer_dropout_prepost=0.1, transformer_feed_forward_num_hidden=(2048, 2048), transformer_model_size=(512, 512), transformer_positional_embedding_type='fixed', transformer_postprocess=('dr', 'dr'), transformer_preprocess=('n', 'n'), update_interval=1, use_cpu=True, validation_source='.//data-bpe//valid.bpe-30000.de', validation_source_factors=[], validation_target='.//data-bpe//valid.bpe-30000.en', weight_decay=0.0, weight_init='xavier', weight_init_scale=3.0, weight_init_xavier_factor_type='avg', weight_init_xavier_rand_type='uniform', weight_normalization=False, weight_tying=False, weight_tying_type='trg_softmax', word_min_count=(1, 1))
[INFO:__main__] Adjusting maximum length to reserve space for a BOS/EOS marker. New maximum length: (101, 101)
[INFO:__main__] Training Device(s): cpu(0)
[ERROR:root] Uncaught exception
Traceback (most recent call last):
  File "/opt/anaconda3/envs/sockeye-curriculum/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/anaconda3/envs/sockeye-curriculum/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/anaconda3/envs/sockeye-curriculum/lib/python3.6/site-packages/sockeye/train.py", line 969, in <module>
    main()
  File "/opt/anaconda3/envs/sockeye-curriculum/lib/python3.6/site-packages/sockeye/train.py", line 835, in main
    train(args)
  File "/opt/anaconda3/envs/sockeye-curriculum/lib/python3.6/site-packages/sockeye/train.py", line 889, in train
    output_folder=output_folder)
  File "/opt/anaconda3/envs/sockeye-curriculum/lib/python3.6/site-packages/sockeye/train.py", line 260, in create_data_iters_and_vocabs
    fill_up=args.fill_up,
AttributeError: 'Namespace' object has no attribute 'fill_up'
`

**Comment by kevinduh** [comment]
@asteria25 ok, I've confirmed this error. 

@Este1le It seems that `fill-up` was removed from `arguments.py` in the Feb 21, 2019 update of version 1.18.77 (master branch). See:

- https://github.com/awslabs/sockeye/commit/02ff337e3370b351b5e2d0c19bbe80a9df8445ec#diff-ada35bd47badf79941fc96f30b2ebf3c
- https://github.com/awslabs/sockeye/pull/593

When you get the chance, can you check what needs to be modified in the `train.py` in curriculum branch which asks for `args.fill_up`? Thanks! 

@mjpost FYI: it seems like our curriculum learning code needs to be updated to reflect changes in `fill-up`. I'm guessing this will be an easy fix on our part, but just want to loop you in just in case.

**Comment by Este1le** [comment]
I've added the --fill-up argument in argument.py and related constants in constant.py in the branch of curriculum. Please try:
```
cd sockeye-curriculum 
git checkout curriculum
git pull
```

**Comment by asteria25** [comment]
The error is fixed,but there's a new error.
TypeError: __init__() got an unexpected keyword argument 'fill_up'

**Comment by Este1le** [comment]
Could you please show the complete error message with the location of the error that occurs included?

**Comment by asteria25** [comment]
Sure.

[ERROR:root] Uncaught exception
Traceback (most recent call last):
  File "/opt/anaconda3/envs/sockeye-curriculum/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/anaconda3/envs/sockeye-curriculum/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/anaconda3/envs/sockeye-curriculum/lib/python3.6/site-packages/sockeye/train.py", line 969, in <module>
    main()
  File "/opt/anaconda3/envs/sockeye-curriculum/lib/python3.6/site-packages/sockeye/train.py", line 835, in main
    train(args)
  File "/opt/anaconda3/envs/sockeye-curriculum/lib/python3.6/site-packages/sockeye/train.py", line 889, in train
    output_folder=output_folder)
  File "/opt/anaconda3/envs/sockeye-curriculum/lib/python3.6/site-packages/sockeye/train.py", line 262, in create_data_iters_and_vocabs
    curriculum_update_freq=args.curriculum_update_freq)
  File "/opt/anaconda3/envs/sockeye-curriculum/lib/python3.6/site-packages/sockeye/data_io.py", line 887, in get_prepared_data_iters
    num_factors=len(data_info.sources))
  File "/opt/anaconda3/envs/sockeye-curriculum/lib/python3.6/site-packages/sockeye/data_io.py", line 1944, in __init__
    label_name=label_name, num_factors=num_factors, dtype=dtype)
TypeError: __init__() got an unexpected keyword argument 'fill_up'

**Comment by Este1le** [comment]
I removed `fill_up=args.fill_up` in train.py and reverted argument.py and constant.py. Please try again:
```
cd sockeye-curriculum 
git checkout curriculum
git pull
```
